using Csls.Control.Contracts;
using Csls.Protocol;
using System.Text.Json.Serialization;

namespace Csls.Cli.Worker;

/// <summary>
/// Provides generated System.Text.Json metadata for versioned CLI response envelopes.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.Never,
    GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(CliError))]
[JsonSerializable(typeof(CliResponseEnvelope))]
[JsonSerializable(typeof(AgentInitResult))]
[JsonSerializable(typeof(DoctorCheck))]
[JsonSerializable(typeof(DoctorCheckStatus))]
[JsonSerializable(typeof(DoctorProject))]
[JsonSerializable(typeof(DoctorReport))]
[JsonSerializable(typeof(SessionWatchEvent))]
[JsonSerializable(typeof(SessionWatchEventKind))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(ControlHoverResult))]
[JsonSerializable(typeof(ControlDocumentPrecondition))]
[JsonSerializable(typeof(ControlEditPlan))]
[JsonSerializable(typeof(ControlApplyEditPlanResult))]
[JsonSerializable(typeof(ControlWorkspaceOperationResult))]
[JsonSerializable(typeof(ControlCancelRequestResult))]
[JsonSerializable(typeof(ControlRequestInfo))]
[JsonSerializable(typeof(ControlRequestSchedulerInfo))]
[JsonSerializable(typeof(ControlTraceEntry))]
[JsonSerializable(typeof(ControlTraceInfo))]
[JsonSerializable(typeof(ControlCodeActionPlan))]
[JsonSerializable(typeof(ControlSessionInfo))]
[JsonSerializable(typeof(ControlWorkspaceInfo))]
[JsonSerializable(typeof(ControlProjectInfo))]
[JsonSerializable(typeof(ControlDocumentInfo))]
[JsonSerializable(typeof(ControlDiagnosticInfo))]
[JsonSerializable(typeof(ControlBuildHostInfo))]
[JsonSerializable(typeof(ControlLogEntry))]
[JsonSerializable(typeof(CompletionItem))]
[JsonSerializable(typeof(CompletionItemKind))]
[JsonSerializable(typeof(CompletionList))]
[JsonSerializable(typeof(CodeAction))]
[JsonSerializable(typeof(CodeActionContext))]
[JsonSerializable(typeof(CodeActionParams))]
[JsonSerializable(typeof(Diagnostic))]
[JsonSerializable(typeof(DiagnosticSeverity))]
[JsonSerializable(typeof(DocumentDiagnosticReport))]
[JsonSerializable(typeof(DocumentSymbol))]
[JsonSerializable(typeof(DocumentHighlight))]
[JsonSerializable(typeof(DocumentHighlightKind))]
[JsonSerializable(typeof(FormattingOptions))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(SignatureHelp))]
[JsonSerializable(typeof(SelectionRange))]
[JsonSerializable(typeof(SignatureInformation))]
[JsonSerializable(typeof(ParameterInformation))]
[JsonSerializable(typeof(SymbolKind))]
[JsonSerializable(typeof(WorkspaceSymbol))]
[JsonSerializable(typeof(WorkspaceSymbolData))]
[JsonSerializable(typeof(WorkspaceSymbolLocation))]
[JsonSerializable(typeof(WorkspaceEdit))]
[JsonSerializable(typeof(TextDocumentEdit))]
[JsonSerializable(typeof(OptionalVersionedTextDocumentIdentifier))]
[JsonSerializable(typeof(IReadOnlyList<ControlSessionInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DoctorCheck>))]
[JsonSerializable(typeof(IReadOnlyList<DoctorProject>))]
[JsonSerializable(typeof(IReadOnlyList<ControlWorkspaceInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlProjectInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlDocumentInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlDiagnosticInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlBuildHostInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlLogEntry>))]
[JsonSerializable(typeof(IReadOnlyList<CompletionItem>))]
[JsonSerializable(typeof(IReadOnlyList<TextEdit>))]
[JsonSerializable(typeof(IReadOnlyList<Location>))]
[JsonSerializable(typeof(IReadOnlyList<Diagnostic>))]
[JsonSerializable(typeof(IReadOnlyList<DocumentSymbol>))]
[JsonSerializable(typeof(IReadOnlyList<DocumentHighlight>))]
[JsonSerializable(typeof(IReadOnlyList<SelectionRange>))]
[JsonSerializable(typeof(IReadOnlyList<WorkspaceSymbol>))]
[JsonSerializable(typeof(IReadOnlyList<SignatureInformation>))]
[JsonSerializable(typeof(IReadOnlyList<ParameterInformation>))]
[JsonSerializable(typeof(IReadOnlyList<CodeAction>))]
[JsonSerializable(typeof(IReadOnlyList<TextDocumentEdit>))]
[JsonSerializable(typeof(IReadOnlyList<ControlDocumentPrecondition>))]
[JsonSerializable(typeof(IReadOnlyList<ControlCodeActionPlan>))]
[JsonSerializable(typeof(IReadOnlyList<ControlRequestInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlTraceEntry>))]
internal sealed partial class CliJsonSerializerContext : JsonSerializerContext;
