<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Csls.Debugger</AssemblyName>
    <RootNamespace>Csls.Debugger</RootNamespace>
    <Description>The NativeAOT-compatible managed .NET debugging engine.</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DiaSymReader" />
    <PackageReference Include="Microsoft.DiaSymReader.Native" />
    <PackageReference Include="Microsoft.Diagnostics.DbgShim" />
    <ProjectReference Include="../Csls.Debugger.Contracts/Csls.Debugger.Contracts.csproj" />
    <ProjectReference Include="../Csls.Debugger.Evaluation/Csls.Debugger.Evaluation.csproj" />
  </ItemGroup>
</Project>
