using Csls.Debugger.Contracts;
using StreamJsonRpc.Protocol;
using System.Text.Json.Serialization;

namespace Csls.Debugger.Control;

/// <summary>
/// Provides NativeAOT-safe JSON metadata for debugger control RPC payloads.
/// </summary>
[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(CommonErrorData))]
[JsonSerializable(typeof(DebugAttachRequest))]
[JsonSerializable(typeof(DebugExceptionBreakpointRequest))]
[JsonSerializable(typeof(DebugExceptionBreakpointSetRequest))]
[JsonSerializable(typeof(DebugExceptionInfo))]
[JsonSerializable(typeof(DebugExceptionInfoRequest))]
[JsonSerializable(typeof(DebugFunctionBreakpointInfo))]
[JsonSerializable(typeof(DebugFunctionBreakpointRequest))]
[JsonSerializable(typeof(DebugFunctionBreakpointSetRequest))]
[JsonSerializable(typeof(DebugGotoRequest))]
[JsonSerializable(typeof(DebugGotoTargetInfo))]
[JsonSerializable(typeof(DebugGotoTargetsRequest))]
[JsonSerializable(typeof(DebugLaunchRequest))]
[JsonSerializable(typeof(DebugDisassembly))]
[JsonSerializable(typeof(DebugDisassemblyRequest))]
[JsonSerializable(typeof(DebugInstructionInfo))]
[JsonSerializable(typeof(DebugInstructionBreakpointInfo))]
[JsonSerializable(typeof(DebugInstructionBreakpointRequest))]
[JsonSerializable(typeof(DebugInstructionBreakpointSetRequest))]
[JsonSerializable(typeof(DebugMemoryReadRequest))]
[JsonSerializable(typeof(DebugMemoryReadResult))]
[JsonSerializable(typeof(DebugScopeInfo))]
[JsonSerializable(typeof(DebugScopesRequest))]
[JsonSerializable(typeof(DebugSessionSnapshot))]
[JsonSerializable(typeof(DebugSourceBreakpointInfo))]
[JsonSerializable(typeof(DebugSourceBreakpointRequest))]
[JsonSerializable(typeof(DebugSourceBreakpointSetRequest))]
[JsonSerializable(typeof(DebugSourceChecksum))]
[JsonSerializable(typeof(DebugSourceContent))]
[JsonSerializable(typeof(DebugSourceInfo))]
[JsonSerializable(typeof(DebugSourceRequest))]
[JsonSerializable(typeof(DebugStackFrameInfo))]
[JsonSerializable(typeof(DebugStackRequest))]
[JsonSerializable(typeof(DebugStackTrace))]
[JsonSerializable(typeof(DebugStepRequest))]
[JsonSerializable(typeof(DebugStepTargetInfo))]
[JsonSerializable(typeof(DebugStepTargetsRequest))]
[JsonSerializable(typeof(DebugSymbolModuleFilterOptions))]
[JsonSerializable(typeof(DebugSymbolOptions))]
[JsonSerializable(typeof(DebugThreadInfo))]
[JsonSerializable(typeof(DebugVariableInfo))]
[JsonSerializable(typeof(DebugVariablesRequest))]
[JsonSerializable(typeof(IReadOnlyList<DebugScopeInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugExceptionBreakpointRequest>))]
[JsonSerializable(typeof(IReadOnlyList<DebugFunctionBreakpointInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugFunctionBreakpointRequest>))]
[JsonSerializable(typeof(IReadOnlyList<DebugGotoTargetInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugInstructionInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugInstructionBreakpointInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugInstructionBreakpointRequest>))]
[JsonSerializable(typeof(IReadOnlyList<DebugSourceBreakpointInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugStepTargetInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugThreadInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DebugVariableInfo>))]
internal sealed partial class DebuggerControlJsonSerializerContext : JsonSerializerContext;
