using Csls.Debugger.Contracts;
using PolyType;
using StreamJsonRpc.Protocol;

namespace Csls.Debugger.Control;

/// <summary>
/// Roots generated type shapes for every private debugger control payload.
/// </summary>
[GenerateShapeFor<int>]
[GenerateShapeFor<CommonErrorData>]
[GenerateShapeFor<DebugAttachRequest>]
[GenerateShapeFor<DebugBreakpointSnapshot>]
[GenerateShapeFor<DebugExceptionBreakpointRequest>]
[GenerateShapeFor<DebugExceptionBreakpointSetRequest>]
[GenerateShapeFor<DebugExceptionInfo>]
[GenerateShapeFor<DebugExceptionInfoRequest>]
[GenerateShapeFor<DebugEvaluateRequest>]
[GenerateShapeFor<DebugEvaluateResult>]
[GenerateShapeFor<DebugExecuteExpressionRequest>]
[GenerateShapeFor<DebugFunctionBreakpointInfo>]
[GenerateShapeFor<DebugFunctionBreakpointRequest>]
[GenerateShapeFor<DebugFunctionBreakpointSetRequest>]
[GenerateShapeFor<DebugGotoRequest>]
[GenerateShapeFor<DebugGotoTargetInfo>]
[GenerateShapeFor<DebugGotoTargetsRequest>]
[GenerateShapeFor<DebugLaunchRequest>]
[GenerateShapeFor<DebugDisassembly>]
[GenerateShapeFor<DebugDisassemblyRequest>]
[GenerateShapeFor<DebugInstructionInfo>]
[GenerateShapeFor<DebugInstructionBreakpointInfo>]
[GenerateShapeFor<DebugInstructionBreakpointRequest>]
[GenerateShapeFor<DebugInstructionBreakpointSetRequest>]
[GenerateShapeFor<DebugMemoryReadRequest>]
[GenerateShapeFor<DebugMemoryReadResult>]
[GenerateShapeFor<DebugModuleInfo>]
[GenerateShapeFor<DebugModulePage>]
[GenerateShapeFor<DebugModulesRequest>]
[GenerateShapeFor<DebugOutputEntry>]
[GenerateShapeFor<DebugOutputPage>]
[GenerateShapeFor<DebugOutputRequest>]
[GenerateShapeFor<DebuggerResourceChangeEventArgs>]
[GenerateShapeFor<DebugScopeInfo>]
[GenerateShapeFor<DebugScopesRequest>]
[GenerateShapeFor<DebugSetExpressionRequest>]
[GenerateShapeFor<DebugSetVariableRequest>]
[GenerateShapeFor<DebugSessionSnapshot>]
[GenerateShapeFor<DebugSourceBreakpointInfo>]
[GenerateShapeFor<DebugSourceBreakpointRequest>]
[GenerateShapeFor<DebugSourceBreakpointSetRequest>]
[GenerateShapeFor<DebugSourceChecksum>]
[GenerateShapeFor<DebugSourceContent>]
[GenerateShapeFor<DebugSourceInfo>]
[GenerateShapeFor<DebugSourceRequest>]
[GenerateShapeFor<DebugStackFrameInfo>]
[GenerateShapeFor<DebugStackRequest>]
[GenerateShapeFor<DebugStackTrace>]
[GenerateShapeFor<DebugStepRequest>]
[GenerateShapeFor<DebugStepTargetInfo>]
[GenerateShapeFor<DebugStepTargetsRequest>]
[GenerateShapeFor<DebugSymbolModuleFilterOptions>]
[GenerateShapeFor<DebugSymbolOptions>]
[GenerateShapeFor<DebugThreadInfo>]
[GenerateShapeFor<DebugVariableInfo>]
[GenerateShapeFor<DebugVariablesRequest>]
[GenerateShapeFor<IReadOnlyList<DebugScopeInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugExceptionBreakpointRequest>>]
[GenerateShapeFor<IReadOnlyList<DebugFunctionBreakpointInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugFunctionBreakpointRequest>>]
[GenerateShapeFor<IReadOnlyList<DebugGotoTargetInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugInstructionInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugInstructionBreakpointInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugInstructionBreakpointRequest>>]
[GenerateShapeFor<IReadOnlyList<DebugOutputEntry>>]
[GenerateShapeFor<IReadOnlyList<DebugSourceBreakpointInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugStepTargetInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugThreadInfo>>]
[GenerateShapeFor<IReadOnlyList<DebugVariableInfo>>]
public sealed partial class DebuggerRpcClient;
