using Csls.Protocol;
using System.Text.Json.Serialization;

namespace Csls.Control.Contracts;

/// <summary>
/// Provides generated System.Text.Json metadata for the versioned control protocol.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(ControlHoverRequest))]
[JsonSerializable(typeof(ControlHoverResult))]
[JsonSerializable(typeof(ControlDiagnosticRequest))]
[JsonSerializable(typeof(ControlCompletionRequest))]
[JsonSerializable(typeof(ControlNavigationRequest))]
[JsonSerializable(typeof(ControlSelectionRangeRequest))]
[JsonSerializable(typeof(ControlDocumentRequest))]
[JsonSerializable(typeof(ControlWorkspaceSymbolRequest))]
[JsonSerializable(typeof(ControlSignatureHelpRequest))]
[JsonSerializable(typeof(ControlRenameRequest))]
[JsonSerializable(typeof(ControlFormattingRequest))]
[JsonSerializable(typeof(ControlCodeActionRequest))]
[JsonSerializable(typeof(ControlCodeActionPlan))]
[JsonSerializable(typeof(ControlDocumentPrecondition))]
[JsonSerializable(typeof(ControlEditPlan))]
[JsonSerializable(typeof(ControlApplyEditPlanRequest))]
[JsonSerializable(typeof(ControlApplyEditPlanResult))]
[JsonSerializable(typeof(ControlSessionInfo))]
[JsonSerializable(typeof(ControlDashboardSnapshot))]
[JsonSerializable(typeof(ControlDashboardRequest))]
[JsonSerializable(typeof(ControlWorkspaceInfo))]
[JsonSerializable(typeof(ControlProjectInfo))]
[JsonSerializable(typeof(ControlDocumentInfo))]
[JsonSerializable(typeof(ControlDiagnosticInfo))]
[JsonSerializable(typeof(ControlRequestSchedulerInfo))]
[JsonSerializable(typeof(ControlBuildHostInfo))]
[JsonSerializable(typeof(ControlCacheInfo))]
[JsonSerializable(typeof(ControlLogEntry))]
[JsonSerializable(typeof(CompletionItem))]
[JsonSerializable(typeof(CompletionItemKind))]
[JsonSerializable(typeof(CompletionList))]
[JsonSerializable(typeof(CodeAction))]
[JsonSerializable(typeof(CodeActionContext))]
[JsonSerializable(typeof(CodeActionParams))]
[JsonSerializable(typeof(Diagnostic))]
[JsonSerializable(typeof(DiagnosticSeverity))]
[JsonSerializable(typeof(DocumentDiagnosticReport))]
[JsonSerializable(typeof(DocumentSymbol))]
[JsonSerializable(typeof(DocumentHighlight))]
[JsonSerializable(typeof(DocumentHighlightKind))]
[JsonSerializable(typeof(FormattingOptions))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(Hover))]
[JsonSerializable(typeof(SignatureHelp))]
[JsonSerializable(typeof(SelectionRange))]
[JsonSerializable(typeof(SignatureInformation))]
[JsonSerializable(typeof(ParameterInformation))]
[JsonSerializable(typeof(SymbolKind))]
[JsonSerializable(typeof(WorkspaceSymbol))]
[JsonSerializable(typeof(WorkspaceSymbolData))]
[JsonSerializable(typeof(WorkspaceSymbolLocation))]
[JsonSerializable(typeof(WorkspaceEdit))]
[JsonSerializable(typeof(TextDocumentEdit))]
[JsonSerializable(typeof(OptionalVersionedTextDocumentIdentifier))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(Position))]
[JsonSerializable(typeof(IReadOnlyList<Diagnostic>))]
[JsonSerializable(typeof(IReadOnlyList<CompletionItem>))]
[JsonSerializable(typeof(IReadOnlyList<TextEdit>))]
[JsonSerializable(typeof(IReadOnlyList<Location>))]
[JsonSerializable(typeof(IReadOnlyList<DocumentSymbol>))]
[JsonSerializable(typeof(IReadOnlyList<DocumentHighlight>))]
[JsonSerializable(typeof(IReadOnlyList<SelectionRange>))]
[JsonSerializable(typeof(IReadOnlyList<WorkspaceSymbol>))]
[JsonSerializable(typeof(IReadOnlyList<SignatureInformation>))]
[JsonSerializable(typeof(IReadOnlyList<ParameterInformation>))]
[JsonSerializable(typeof(IReadOnlyList<CodeAction>))]
[JsonSerializable(typeof(IReadOnlyList<TextDocumentEdit>))]
[JsonSerializable(typeof(IReadOnlyList<ControlDocumentPrecondition>))]
[JsonSerializable(typeof(IReadOnlyList<ControlCodeActionPlan>))]
[JsonSerializable(typeof(IReadOnlyList<ControlWorkspaceInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlProjectInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlDocumentInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlDiagnosticInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlBuildHostInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlCacheInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ControlLogEntry>))]
public sealed partial class ControlJsonSerializerContext : JsonSerializerContext;
